import os

KAFKA_BOOTSTRAP_SERVERS = os.getenv('KAFKA_BOOTSTRAP_SERVERS')
KAFKA_PRODUCER_USERNAME = os.getenv('KAFKA_PRODUCER_USERNAME')
KAFKA_PRODUCER_PASSWORD = os.getenv('KAFKA_PRODUCER_PASSWORD')
KAFKA_CONSUMER_USERNAME = os.getenv('KAFKA_CONSUMER_USERNAME')
KAFKA_CONSUMER_PASSWORD = os.getenv('KAFKA_CONSUMER_PASSWORD')
USERS_VIEWS_FILMS_TOPIC = 'users_views_films'

CLICKHOUSE_USER = os.getenv('CLICKHOUSE_USER')
CLICKHOUSE_PASSWORD = os.getenv('CLICKHOUSE_PASSWORD')
CLICKHOUSE_URL = os.getenv('CLICKHOUSE_URL')
ETL_SENTRY_DSN = os.getenv('ETL_SENTRY_DSN')