name: Deployment Workflow
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Style checking
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./api/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ./etl/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./api/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          flake8 ./etl/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Type checking
        run: |
          mypy ./api
          mypy ./etl

  notify:
    runs-on: ubuntu-20.04
    if: always()
    needs: build
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>${{ github.workflow }}</b> run results

            <b>repository</b>: <a href="https://github.com/${{github.repository}}">${{github.repository}}</a>
            <b>event</b>: ${{ github.event_name }}
            <b>status</b>: ${{ needs.build.result }}
            <b>details</b>: <a href="https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}">Click to view</a>
